### ISSUE TITLE
Docker container only displays what is currently playing

### ISSUE THREAD

**Issue by Zanaso12** [tenasi/plexannouncer#1]
I've been using this container for about a week now and it only writes to the discord server when something is currently playing, regardless if it is in your list of monitored libraries or not. 

![image](https://user-images.githubusercontent.com/15000271/112191098-465c2d00-8bcb-11eb-8aa6-9c45f3f4fdb8.png)

This could be user error, as there is no dileniation of how the "Updated Libraries" env variable should be formatted, at least not in Unraid or the readme for this container.

Ideally, I don't want to bot to show what's currently playing, and only show what new content has been added to the server, based on libraries that I specify.

**Comment by jonpetersathan** [comment]
Does that issue still persist with the latest version?
