### ISSUE TITLE
Error Handling Request

### ISSUE THREAD

**Issue by callumgourlay** [tenasi/plexannouncer#2]
Hello,

When i update any library i just get this error in my log 

`Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"`

**Comment by jonpetersathan** [comment]
Should be fixed by now, this was due to an issue with aiohttp. Can you confirm?

**Comment by callumgourlay** [comment]
Can confirm this is resolved now since a recent update :)
