### ISSUE TITLE
Not triggered when media added

### ISSUE THREAD

**Issue by ThatNerdUKnow** [tenasi/plexannouncer#3]
Hi, I have this container running on my unraid server and the bot does seem to be receiving webhooks but never any for media addition. For example here's some logs

```
Request rejected. Event type of media.pause.
Inbound request
Request rejected. Event type of media.resume.
Inbound request
Request rejected. Event type of media.pause.
Inbound request
Request rejected. Event type of media.resume.
Inbound request
Request rejected. Event type of media.stop.
Inbound request
Request rejected. Event type of media.play.
Inbound request
Request rejected. Event type of media.pause.
Inbound request
Request rejected. Event type of media.resume.
Inbound request
```

So it does seem that the container is recieving the webhooks but isn't getting webhooks for media addition

**Comment by jonpetersathan** [comment]
Can you check both of these settings again:

Plex Server Settings / Network / Webhooks (Advanced View)
Plex Server Settings / General / Push Notifications (Advanced View)

Both of them should be checked.

**Comment by ThatNerdUKnow** [comment]
Webhooks are enabled and I can see in the container logs that events media.resume media.stop media.play media.pause and media.resume are all firing but for some reason the new media hook isn't fired. I believe that my webhooks are configured correctly but I can double check these settings when I get home

**Comment by ThatNerdUKnow** [comment]
I checked on my phone and push notifications were disabled. How can I test to see if this did the trick short of removing some media from my library and doing the plex dance?

**Comment by jonpetersathan** [comment]
Push Notifications should also be enabled in the web app, your phone doesn't matter here, there is also an option in the web app. Make sure to enable advanced view, so the option is displayed. After enabling push notification you can either rename a random file with a movie title and put it in your folder or you remove an existing file, wait a couple of minutes and add it again.

**Comment by ThatNerdUKnow** [comment]
I found that omitting the libraries environment variable fixes this issue. Simply having the variable left as blank (as is default on the unraid preset from the unraid community apps) rejects every event from every library. Removing the variable completely resolved the issue
